export const LOADING = "LOADING";

export const ERROR = "ERROR";

export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";

export const SAVE_EDITED_TASK_SUCCESS = "SAVE_EDITED_TASK_SUCCESS";

export const REMOVE_ALL_SUCCESS = "REMOVE_ALL_SUCCESS";

export const REMOVE_SELECTED_SUCCESS = "REMOVE_SELECTED_SUCCESS";

export const OPEN_ONE_TASK_SUCCESS = "OPEN_ONE_TASK_SUCCESS";

export const REMOVE_ONE_TASK_SUCCESS = "REMOVE_ONE_TASK_SUCCESS";

export const SAVE_ONE_TASK_SUCCESS = "SAVE_ONE_TASK_SUCCESS";
